apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    track: "{{ .Values.application.track }}"
    tier: "{{ .Values.application.tier }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      track: "{{ .Values.application.track }}"
      tier: "{{ .Values.application.tier }}"
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        track: "{{ .Values.application.track }}"
        tier: "{{ .Values.application.tier }}"
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: EXCHANGESERVICE
          valueFrom:
            secretKeyRef:
              name: strategy-secrets
              key: exchange-service
        - name: MONGODBNAME
          valueFrom:
            secretKeyRef:
              name: strategy-secrets
              key: mongodbname
        - name: MONGODB
          valueFrom:
            secretKeyRef:
              name: strategy-secrets
              key: mongodb
        - name: NATS
          valueFrom:
            secretKeyRef:
              name: strategy-secrets
              key: nats
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: strategy-secrets
              key: redis-host
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: strategy-secrets
              key: redis-port
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: strategy-secrets
              key: redis-password
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: strategy-secrets
              key: db-host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: db-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: db-password 
        - name: OHLCDB_NAME
          valueFrom:
            secretKeyRef:
              name: strategy-secrets
              key: db-name
        - name: OHLCV_TABLE_NAME
          valueFrom:
            secretKeyRef:
              name: strategy-secrets
              key: db-table-name
        ports:
        - name: "{{ .Values.service.name }}"
          containerPort: {{ .Values.service.internalPort }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: 60
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: 60
          timeoutSeconds: 30
        resources:
{{ toYaml .Values.resources | indent 12 }}
